[FIX] the package managmement for doxygen workflow, job export_other_formats_when_possible

diff --git a/.github/workflows/doxygen_generator.yaml b/.github/workflows/doxygen_generator.yaml
--- a/.github/workflows/doxygen_generator.yaml
+++ b/.github/workflows/doxygen_generator.yaml
@@ -933,16 +933,18 @@ jobs:
       
       - name: Install the zip binary if not present
         run: |
-          zip --version >/dev/null 2>/dev/null
-          if [ $? -ne 0 ]; then
-            echo "zip is not installed, installing"
-            sudo apt install -y zip
+          sudo apt update
+          sudo apt install -y zip unzip
+          zip --version >/dev/null 2>&1
+          STATUS=$?
+          if [ $STATUS -ne 0 ]; then
+            echo "::error file=<none>,line=0,endLine=0,title=zip is not installed::$STATUS"
           fi
 
-          unzip --version >/dev/null 2>/dev/null
-          if [ $? -ne 0 ]; then
-            echo "unzip is not installed, installing"
-            sudo apt install -y unzip
+          unzip --version >/dev/null 2>&1
+          STATUS=$?
+          if [ $STATUS -ne 0 ]; then
+            echo "::error file=<none>,line=0,endLine=0,title=unzip is not installed::$STATUS"
           fi
       
       - name: Compressing the folders into archives
